[project]
name = "python-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.25",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
