[project]
name = "python-langchain"
version = "5.0.0"
description = "langchain App"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.25",
    "langchain-openai>=0.3.23",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
